### PR TITLE
ODPI-26 - Added appendix with internal Hadoop config values.

### PR DESCRIPTION
**Pull request by alanfgates**
I went with the verbose version which includes a large number of config values.  If people think we should be more concise and for example only include security values let me know.  Also, feedback to make sure I didn't put anything on the list that your apps use is highly appreciated.

### CODE REVIEW

**Comment by brian-rickman** [comment]
I think the list of config values would be more useful if it was sorted, but otherwise this looks good.

**Comment by aw-was-here** [comment]
Agreed that the list should be alphabetical.

**Comment by alanfgates** [comment]
Ok, I've sorted the list and merged in the latest changes from master.  I don't seem to have permission to close the pull request.

**Comment by aw-was-here** [comment]
No one can without ICLA bits in place.  :8ball:

**Comment by jmertic** [comment]
@alanfgates is there an update on getting the CCLA signed by HWX?

**Comment by jmertic** [comment]
@alanfgates Any updates? We would probably need to reschedule the RT call if this can't be resolved in the next 2 hours.

**Comment by jctanner** [comment]
Alan, can you clarify "shared by"? In a distro, how are these settings "shared"? What would a test for this look like?

**Comment by jmertic** [comment]
Pinging @alanfgates to respond to @jctanner 's note

**Comment by alanfgates** [comment]
@jctanner , sorry I only saw your question after I merged the pull request.  If you want to clarify the language in the spec feel free to open a new JIRA on it and assign it to me.

Earlier in the spec it says:

> ODPi Platforms SHOULD publish all modified (i.e., not-default) Apache Hadoop configuration entries, regardless of client, server, etc applicability to all nodes unless it is known to be node hardware specific, private to a service, security-sensitive, or otherwise problematic. The list of variables that SHOULD NOT be shared are listed in Appendix A.

So this is the list that doesn't have to be published.  It would probably be better if we used the word published consistently rather than switching to "shared".

**Comment by jmertic** [comment]
@jctanner Did you open a separate JIRA ticket for this? Might make sense to do so since this has merged already.

**Comment by jctanner** [comment]
I think @alanfgates correctly pointed out that a different section of the spec is where "publication" should be clarified. I did not open a JIRA, but I think the definition will get clarified when someone has to write a test for the section @alanfgates cited.

**Comment by jmertic** [comment]
OK, sounds good.

**Pull request merged**
